apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-5ws8
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-sjak-tenant/rhtap-demo-app/hacbs-test-project-5ws8@sha256:09aa7f0cca36ded89c4f6bd75bd3407c9dabd3a3069a733182523936ccb75a56
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
