apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-5ws8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-5ws8
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-5ws8
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-5ws8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-5ws8
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-sjak-tenant/rhtap-demo-app/hacbs-test-project-5ws8@sha256:2852df74b9396ce7fc58b0bb948f367374ac4a32458bff268f1195ef805f3d4d
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
